### ISSUE TITLE
Remove unwanted files

### ISSUE THREAD

**Issue by nadunys** [acicts/bits-official#1]
Remove the .docx files and compress the .pdf files
[http://pdfcompressor.com](http://pdfcompressor.com) << use this
@STEdirisuriya

**Comment by Binxth** [comment]
Done 👍

**Comment by Binxth** [comment]
Compress the .pdf files @STEdirisuriya

**Comment by nadunys** [comment]
@Binath check grammar errors

**Comment by Binxth** [comment]
Kay

**Comment by Binxth** [comment]
Done 👍  @yashNadun

**Comment by supunTE** [comment]
When I compress a .pdf, all the links are not working. It turns our pdf into a image. links are not working.

**Comment by nadunys** [comment]
Then keep it the way it is, next time do not use PDFs.
